export const navigationLinks = [
    {
        id:'home',
        title:'Home'
    },
    {
        id:'about',
        title:'About'
    },
    {
        id:'page',
        title:'Page'
    },
    {
        id:'blog',
        title:'Blog'
    },
    {
        id:'contact',
        title:'Contact'
    },
]